/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:66f3f7d7929306bf250b54da1f20aa3c91b0f1c1 

#pragma once

#include "Keranous_pcie_tileMirrorBase.h"



class Keranous_pcie_tileMirror : public Keranous_pcie_tileMirrorBase {
  public:
#if (defined SYSTEMC_VERSION && SYSTEMC_VERSION <= 20221128 /*2.3.4*/)
    SC_HAS_PROCESS(Keranous_pcie_tileMirror);
#endif

    Keranous_pcie_tileMirror(sc_core::sc_module_name name) : Keranous_pcie_tileMirrorBase(name) {
    }
};

